[package]
edition      = "2024"
name         = "esp32s3_esp_now_button_led"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "esp32s3_esp_now_button_led"
path = "./src/bin/main.rs"

[dependencies]
esp-alloc = "0.10.0"
esp-hal = { version = "~1.1.0", features = ["esp32s3", "unstable", "defmt"] }
esp-radio = { version = "0.18.0", features = ["esp-now", "esp32s3", "unstable", "defmt", "wifi"] }
esp-rtos = { version = "0.3.0", features = ["embassy", "esp32s3", "esp-radio"] }

esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }

embassy-executor = { version = "0.10.0", features = [] }
embassy-sync = "0.8.0"
embassy-time     = "0.5.0"

critical-section = "1.2.0"
static_cell      = { version = "2.1.1", features = ["nightly"] }
defmt = "1.1.0"
defmt-rtt = "1.2.0"

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
